**10 marks written question:** short questions, mostly focusing on Numpy

**10 marks lab task:** a slight variation to the lab tasks shown in class, you need to write simple code and explanation

Import necessary modules and libraries

In [31]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

Normal Distribution

In [32]:
np.random.seed(5)
np.random.normal(50,10,10) #(mean, std, number of elements) so, range = 50 +- 10 = 40 to 50

array([54.41227487, 46.69129848, 74.30771187, 47.4790787 , 51.09609842,
       65.82481117, 40.90767595, 44.08363342, 51.87603226, 46.70130042])

Std normal distribution (mean = 0, std = 1)

In [33]:
a = [[3, 4], [7, 8]]
b = [[1, 2], [5, 6]]

c = []

for i in range(len(a)):
    pass

In [34]:
import pandas as pd

df = pd.read_csv("index_1.csv")

df.head()

date                 datetime cash_type                 card  money  \
0  2024-03-01  2024-03-01 10:15:50.520      card  ANON-0000-0000-0001   38.7   
1  2024-03-01  2024-03-01 12:19:22.539      card  ANON-0000-0000-0002   38.7   
2  2024-03-01  2024-03-01 12:20:18.089      card  ANON-0000-0000-0002   38.7   
3  2024-03-01  2024-03-01 13:46:33.006      card  ANON-0000-0000-0003   28.9   
4  2024-03-01  2024-03-01 13:48:14.626      card  ANON-0000-0000-0004   38.7   

     coffee_name  
0          Latte  
1  Hot Chocolate  
2  Hot Chocolate  
3      Americano  
4          Latte

In [35]:
x = np.random.normal(50,10,10)
x

array([38.07235388, 47.95123489, 46.41171053, 56.03471603, 33.35211471,
       42.99820962, 61.51391009, 68.57331007, 34.88820442, 56.44847511])

In [36]:
l = np.log(x)
l

array([3.6394884 , 3.87018455, 3.83755181, 4.02597143, 3.50712118,
       3.76115848, 4.11926333, 4.22790339, 3.55214879, 4.03332828])

In [37]:
mean = np.mean(l)
mean

np.float64(3.857411963833054)

In [38]:
print(np.exp(mean))

47.34266814562052


In [39]:
print(f"Geometric mean: {np.exp(np.mean(np.log(x)))}")

Geometric mean: 47.34266814562052


In [40]:
x

array([38.07235388, 47.95123489, 46.41171053, 56.03471603, 33.35211471,
       42.99820962, 61.51391009, 68.57331007, 34.88820442, 56.44847511])

In [41]:
tips = sns.load_dataset('tips')
tips.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [42]:
summary = tips.groupby("day")['tip'].agg(['count', 'mean', 'median', 'min', 'max', 'std', 'var'])
# pd.DataFrame(summary)
summary

C:\Users\mushf\AppData\Local\Temp\ipykernel_13104\1259193641.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  summary = tips.groupby("day")['tip'].agg(['count', 'mean', 'median', 'min', 'max', 'std', 'var'])


count      mean  median   min    max       std       var
day                                                           
Thur     62  2.771452   2.305  1.25   6.70  1.240223  1.538154
Fri      19  2.734737   3.000  1.00   4.73  1.019577  1.039537
Sat      87  2.993103   2.750  1.00  10.00  1.631014  2.660208
Sun      76  3.255132   3.150  1.01   6.50  1.234880  1.524929

In [43]:
df.head()

date                 datetime cash_type                 card  money  \
0  2024-03-01  2024-03-01 10:15:50.520      card  ANON-0000-0000-0001   38.7   
1  2024-03-01  2024-03-01 12:19:22.539      card  ANON-0000-0000-0002   38.7   
2  2024-03-01  2024-03-01 12:20:18.089      card  ANON-0000-0000-0002   38.7   
3  2024-03-01  2024-03-01 13:46:33.006      card  ANON-0000-0000-0003   28.9   
4  2024-03-01  2024-03-01 13:48:14.626      card  ANON-0000-0000-0004   38.7   

     coffee_name  
0          Latte  
1  Hot Chocolate  
2  Hot Chocolate  
3      Americano  
4          Latte

In [44]:
summary_2 = df.groupby('cash_type')['money'].agg(['count', "mean", 'median', 'min', 'max', 'std', 'var'])
summary_2

count       mean  median    min   max       std        var
cash_type                                                            
card        3547  31.645216   32.82  18.12  38.7  4.877754  23.792481
cash          89  35.797753   39.00  24.00  40.0  4.910980  24.117722

In [45]:
summary_3 = df.groupby('coffee_name')['money'].agg(['count', "mean", 'median', 'min', 'max', 'std', 'var'])
summary_3

count       mean  median    min   max       std       var
coffee_name                                                                   
Americano              578  26.059273   25.96  23.02  30.0  1.740508  3.029367
Americano with Milk    824  30.666408   30.86  27.92  35.0  1.940697  3.766306
Cappuccino             501  35.996287   35.76  32.82  40.0  1.906202  3.633608
Cocoa                  243  35.712593   35.76  32.82  40.0  1.307759  1.710233
Cortado                292  25.804315   25.96  23.02  30.0  2.148458  4.615873
Espresso               134  21.002090   21.06  18.12  25.0  2.078350  4.319538
Hot Chocolate          282  36.072553   35.76  32.82  40.0  1.527680  2.333808
Latte                  782  35.634655   35.76  32.82  40.0  1.936673  3.750704

In [46]:
tips

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [49]:
tips.loc[tips['day'] == "Sun"]

total_bill   tip     sex smoker  day    time  size
0         16.99  1.01  Female     No  Sun  Dinner     2
1         10.34  1.66    Male     No  Sun  Dinner     3
2         21.01  3.50    Male     No  Sun  Dinner     3
3         23.68  3.31    Male     No  Sun  Dinner     2
4         24.59  3.61  Female     No  Sun  Dinner     4
..          ...   ...     ...    ...  ...     ...   ...
186       20.90  3.50  Female    Yes  Sun  Dinner     3
187       30.46  2.00    Male    Yes  Sun  Dinner     5
188       18.15  3.50  Female    Yes  Sun  Dinner     3
189       23.10  4.00    Male    Yes  Sun  Dinner     3
190       15.69  1.50    Male    Yes  Sun  Dinner     2

[76 rows x 7 columns]

In [52]:
tips.loc[tips['day'] == "Sun", ['total_bill', 'tip']]

total_bill   tip
0         16.99  1.01
1         10.34  1.66
2         21.01  3.50
3         23.68  3.31
4         24.59  3.61
..          ...   ...
186       20.90  3.50
187       30.46  2.00
188       18.15  3.50
189       23.10  4.00
190       15.69  1.50

[76 rows x 2 columns]

In [54]:
days = tips['day'].unique()

for i, d in enumerate(days):
    vals = tips.loc[tips['day'] == d, 'total_bill']
    print(vals)

0      16.99
1      10.34
2      21.01
3      23.68
4      24.59
       ...  
186    20.90
187    30.46
188    18.15
189    23.10
190    15.69
Name: total_bill, Length: 76, dtype: float64
19     20.65
20     17.92
21     20.29
22     15.77
23     39.42
       ...  
238    35.83
239    29.03
240    27.18
241    22.67
242    17.82
Name: total_bill, Length: 87, dtype: float64
77     27.20
78     22.76
79     17.29
80     19.44
81     16.66
       ...  
202    13.00
203    16.40
204    20.53
205    16.47
243    18.78
Name: total_bill, Length: 62, dtype: float64
90     28.97
91     22.49
92      5.75
93     16.32
94     22.75
95     40.17
96     27.28
97     12.03
98     21.01
99     12.46
100    11.35
101    15.38
220    12.16
221    13.42
222     8.58
223    15.98
224    13.42
225    16.27
226    10.09
Name: total_bill, dtype: float64
