**10 marks written question:** short questions, mostly focusing on Numpy

**10 marks lab task:** a slight variation to the lab tasks shown in class, you need to write simple code and explanation

Import necessary modules and libraries

In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

Normal Distribution

In [5]:
np.random.seed(5)
np.random.normal(50,10,10) #(mean, std, number of elements) so, range = 50 +- 10 = 40 to 50

array([54.41227487, 46.69129848, 74.30771187, 47.4790787 , 51.09609842,
       65.82481117, 40.90767595, 44.08363342, 51.87603226, 46.70130042])

Std normal distribution (mean = 0, std = 1)

In [6]:
a = [[3, 4], [7, 8]]
b = [[1, 2], [5, 6]]

c = []

for i in range(len(a)):
    pass

In [7]:
import pandas as pd

df = pd.read_csv("index_1.csv")

df.head()

date                 datetime cash_type                 card  money  \
0  2024-03-01  2024-03-01 10:15:50.520      card  ANON-0000-0000-0001   38.7   
1  2024-03-01  2024-03-01 12:19:22.539      card  ANON-0000-0000-0002   38.7   
2  2024-03-01  2024-03-01 12:20:18.089      card  ANON-0000-0000-0002   38.7   
3  2024-03-01  2024-03-01 13:46:33.006      card  ANON-0000-0000-0003   28.9   
4  2024-03-01  2024-03-01 13:48:14.626      card  ANON-0000-0000-0004   38.7   

     coffee_name  
0          Latte  
1  Hot Chocolate  
2  Hot Chocolate  
3      Americano  
4          Latte

In [8]:
x = np.random.normal(50,10,10)
x

array([38.07235388, 47.95123489, 46.41171053, 56.03471603, 33.35211471,
       42.99820962, 61.51391009, 68.57331007, 34.88820442, 56.44847511])

In [11]:
l = np.log(x)
l

array([3.6394884 , 3.87018455, 3.83755181, 4.02597143, 3.50712118,
       3.76115848, 4.11926333, 4.22790339, 3.55214879, 4.03332828])

In [13]:
mean = np.mean(l)
mean

np.float64(3.857411963833054)

In [14]:
print(np.exp(mean))

47.34266814562052


In [15]:
print(f"Geometric mean: {np.exp(np.mean(np.log(x)))}")

Geometric mean: 47.34266814562052
